config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resources :albums do
    resources :photos
  end
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :date_of_event, type: Date
  field :about, type: String

  embeds_many :photos, cascade_callbacks: true
  belongs_to :user

  accepts_nested_attributes_for :photos

end

app/models/photo.rb
class Photo
  include Mongoid::Document
  field :caption, type: String

  mount_uploader :image, PhotoUploader

  embedded_in :album
  

 
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :summary, type: String
  field :password_digest, type: String
  attr_reader :password

  mount_uploader :avatar, AvatarUploader

  has_many :albums

  def password=(unencrypted_password)
  	unless unencrypted_password.empty?
  		@password = unencrypted_password
  		self.password_digest = BCrypt::Password.create(unencrypted_password)
  	end
  end

  def authenticate(unencrypted_password)
  	if BCrypt::Password.new(self.password_digest) == unencrypted_password
  		return self
  	else
  		return false
  	end
  end

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, length:{in:6..20}, confirmation: true, on: :create
  validates :password, length:{in:6..20}, confirmation: true, on: :update, allow_blank: true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index	
		@albums = Album.all

	end
	def show
		@album = Album.find(params[:id])
	end
	def new
		@album = Album.new
		@album.photos.build

	end
	def create
		@album = Album.new(album_params)
		@album.user = current_user
		photo_params[:image].each {|p| @album.photos.new(image: p)}


		if @album.save
			redirect_to album_path(@album)

		else
			render :new
		end
	end
	def edit
	end
	def update
	end
	def destroy
	end
	def date_published
      created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
    end

	private
	def album_params
		params.require(:album).permit(:name, :time_of_trip, :about, :user)
	end

	private
	def photo_params
		params.require(:album).require(:photo).permit(:caption, :image => [])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@photos = Photo.all
	end
	def show
		@album = Album.find(params[:album_id])
		@photo = @album.photos.find(params[:id])
	end
	def new
		@album = Album.find(params[:album_id])
		@photo = Photo.new
		@photo = @album.photos.build
	end
	def create
		@album = Album.find(params[:album_id])
		#@photo = @album.photos.build(photo_params_create)
		
		photo_params_create[:image].each {|p| @album.photos.new(image: p)}


		if @album.save
			redirect_to album_path(@album)
		else
			render :new
		end
	end
	def edit
		@album = Album.find(params[:album_id])
		@photo = @album.photos.find(params[:id])

	end
	def update
		@album = Album.find(params[:album_id])
		@photo = @album.photos.find(params[:id])
		if @photo.update_attributes(photo_params_update)
			redirect_to album_photo_path
		else
			render "edit"
		end
	end
	def destroy
		@album = Album.find(params[:album_id])
		@photo = @album.photos.find(params[:id])
		if @photo.destroy
			redirect_to album_path(@album)
		else
			render "edit"
		end
	end

	def photo_params_update
		params.require(:photo).permit(:caption, :image => [])
	end	
	def photo_params_create
		params.require(:album).require(:photo).permit(:caption, :image => [])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.where(email: params[:login][:email]).first
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to users_path
		else
			flash[:fail] = "Log in failed"
			redirect_to login_path
		end
	end
	def destroy
		session.delete(:user_id)
		redirect_to users_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to root_path
		else
			render :new
		end
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path
		else
			render "edit"
		end
	end
	def destroy
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find(session[:user_id])
	end
	def logged_in?
  		session[:user_id] != nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<%= render "shared/nav" %>


<div class="jumbotron">

	<h1><%= current_user.name %>'s Adventures</h1>
		
		<div>
			<% current_user.albums.each do |album| %>
				
					<div><%= link_to album.name, album_path(album) %></div>

						<% if !album.photos.empty? %>
							<div><%=link_to (image_tag album.photos[0].image.url(:default)), album_path(album) %></div>	
						<% end %>
			
					<div><%= album.about %></div>
	
			<%end%>

		</div>

	<button class="createalbum"><%= link_to "Create New Album", new_album_path %></h2></button>
</div>

app/views/albums/new.html.erb
<%= render "shared/nav" %>

<div class="jumbotron">

	<div class="newalbum">
		<h1>CREATE A NEW ALBUM</h1>

		<%= form_for @album do |f| %>

			<div>
				<%= f.label :name%>
				<%= f.text_field :name %>
			</div>
			<div>
				<%= f.label :date_of_event%>
				<%= f.date_field :date_of_event %>
			</div>
			<div>
				<%= f.label :about %>
				<%= f.text_area :about  %>
			</div>

			<div class="add-photo">
				<h3>Add Photos</h3>

				
				<%= f.fields_for @album.photos do |photo_fields| %>
					<div>
						<%= photo_fields.file_field :image, multiple: true %>
					</div>
			
				<% end %>
			</div>

			<div>
				<%= f.submit "Create Your Album" %>
			</div>
		<% end %>
	</div>
</div>

app/views/albums/show.html.erb
<%= render "shared/nav" %>

	<div class="jumbotron">



			<div class="album-name">
				<h1><%= @album.name %></h1>
			</div>
			<div>
				<%= @album.about %>
			</div>

			<% @album.photos.each do |photo| %>
				<%= link_to (image_tag photo.image.url(:default)), album_photo_path(@album, photo) %>
			<% end %>
			<div>
				<button class="createalbum .col-md-1"><%= link_to "Back", albums_path %></button>	
				<button class="createalbum .col-md-1"><%= link_to "Add Photo", new_album_photo_path(@album) %></button>
		
			</div>

	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<%= render "shared/nav" %>

<div class="jumbotron">
	<%= image_tag @photo.image.url(:default) %>

	<div>
		<%= form_for [@album, @photo] do |f| %>
			<div>
				<%= f.label :caption %>
			</div>
			<div>
				<%= f.text_area :caption %>
			</div>
			<div>
				<%= f.submit :submit %>
			</div>
		<% end %>
	</div>

</div>

app/views/photos/new.html.erb
<%= render "shared/nav" %>

<div class="jumbotron">

	<div class="row add-photo">
		<%= form_for @album, url: album_photos_path(@album), method: 'post' do |f| %>
				<%= f.fields_for @album.photos do |photo_fields| %>
					<div class="">
						<%= photo_fields.file_field :image, multiple: true %>
					</div>
					
				<% end %>
				<div>
					<%= f.submit "submit" %>
				</div>
		<% end %>
	</div>
</div>

app/views/photos/show.html.erb
<%= render "shared/nav" %>

<div class="jumbotron">


	<div><%= image_tag @photo.image.url(:default) %></div>

	<div><%= @photo.caption %></div>

	<% if !@photo.caption %>
		<div>
			<button><%= link_to "Add Caption!", edit_album_photo_path %></button>
		</div>
	<% else %>
			<button><%= link_to "Edit Caption!", edit_album_photo_path %></button>
	<% end %>

		<button><%= link_to "Delete this Photo", :album_photo, method: :delete, data:{ confirm: "Are you sure?"} %></button>
		<button><%= link_to "Back to Album", album_path(@album) %></button>

</div>

app/views/shared/_nav.html.erb
<!-- Navbar -->
<nav class="navbar navbar-inverse"> 

	<!-- Row-fluid -->
	<div class="container-fluid">
		 <div class="row"> 
			<div class="col-md-10 text-left btn-group">
					
					  <button type="button" class="btn btn-default btn-lg"><%= link_to 'Home', users_path %></button>
					
					<% if logged_in? %>   

					  <button type="button"
					  class="btn btn-default btn-lg" role="button"><%= link_to 'Your Profile', user_path(current_user) %></button>			  
					  <button type="button" class="btn btn-default btn-lg"><%= link_to 'Your Albums', albums_path %></button>

					  <button type="button" class="btn btn-default btn-lg"><%= link_to 'Edit Profile', edit_user_path(current_user) %></button>

					<% end %>
							
			<!-- End col-md-6 -->
			</div>

			<div class="col-md-2 text-right">

				<% if logged_in? %>   
					<button type="button" class="btn btn-default btn-lg"><%= link_to 'Log Out', logout_path, method: :delete %></button>
				<% else %>
					<div class="row">
					<button type="button" class="btn btn-default btn-lg text-left",""><%= link_to "SignUp", new_user_path %></button>
				 	<button type="button" class="btn btn-default btn-lg text_right"><%= link_to 'Log In', login_path  %></button>
				 	<div>
				<% end %>

			<!-- End col-md-6 -->	
			</div>
		</div>
	<!-- End Row-fluid -->
	</div>

<!-- End Navbar -->
</nav>

app/views/users/edit.html.erb
<%= render "shared/nav" %>

<div class = "jumbotron">
	<h1>Edit your profile</h1>

	<% @user.errors.full_messages.each do |msg|
	 %>
	 	<p>
	 		<%= msg %>
	 	</p>
	 <% end %>

	<div class="add-photo">
		<%= form_for @user do |f| %>
			<div>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>
			<div>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>	
			<div>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</div>
			<div>
				<%= f.label :avatar, "Change display picture" %>
				<%= f.file_field :avatar %>
			</div>
			<div>
				<%= f.submit "Confirm" %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<%= render "shared/nav" %>

<div class="jumbotron">
	<h1>Travelers Log</h1>
	<h3>Keep track of your adventures</h3>

	<div class="container">
		<% if logged_in? %>

				<h2>Welcome Back <%= current_user.name %></h2>

				<button type="button" class="btn btn-default"><%= link_to 'Your adventures', albums_path %></button>

				<button type="button" class="btn btn-default"><%= link_to 'Log Out', logout_path, method: :delete %></button>

			<% else %>

				<h2>Welcome </h2>

				<button type="button" class="btn btn-default"><%= link_to "SignUp", new_user_path %></button>

				<button type="button" class="btn btn-default"><%= link_to 'Log In', login_path  %></button>

		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<%= render "shared/nav" %>

<div class="jumbotron row text-center">
	<h1>Signup</h1>

	<ul class="errors">

	  <% @user.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>

	</ul>
	<div class="add-photo">
		<%= form_for @user do |f| %>
			<div>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>
			<div>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>
			<div>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</div>
			<div >
				<%= f.label :avatar %>
				<%= f.file_field :avatar %>
			</div>
			<div>
				<%= f.submit "SIGN UP" %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= render "shared/nav" %>

<div class = "jumbotron">

	<%= image_tag @user.avatar.url(:thumb) %>

	<div><%= current_user.name %></div>
	<div><%= current_user.email %></div>
	<div>You have been on <%= current_user.albums.length %> adventure(s)</div>
	

</div>